#+TITLE: Genome Wide Association Study of Scar Size in ALSPAC
#+AUTHOR: Sam Neaves

* About

This notebook is written as an [[https://orgmode.org][emacs Org file]] and exported into HTML
and PDF formats. 
Org files are plain text and can be viewed with any plain text file
viewer. 
In addition if the file is opened in emacs, interactive features of
running the code in the code blocks can be used using a feature called
[[https://orgmode.org/worg/org-contrib/babel/][org babel]].
The GIT hub repositry is https://github.com/samwalrus/gwas_scar. 
This contains a record of previous versions of the notebook.
Code blocks are in Bash, R and Prolog (only the subset required for
defining makeprog files for Biomake.)
The programming style of mixing prose and code blocks in notebooks is
a type of [[https://en.wikipedia.org/wiki/Literate_programming][literate programmig]].

This notebook and assoicated code can be read in a number of ways.
Firstly it be read as a fixed record of the code that was run and the
results obtained at the time on the hardware used by myself.
Secondly it can be run interactivly step by step where a reader is
able to modify code blocks to explore the coded paramter space as well
as add or remove lines of code.
Thirdly it can be read as instructions to run the code exactly as part
of a pipeline.

** Initial Setup for interactive code.

This code is designed to be open and rerunable. 
Some aspects of running code on a particular system at a particular
time may need to be modified.
The following instruction give details on how to run this code on the
university of bristol HPC machine blue crystal phase 4 in the summer
of 2022.
BC4 uses the slurm job schedular in order to fairly share the compute
resources. 
The compute resources in HPC machines are commonly controled by login
nodes that utilize compute nodes.
To run the R code in this note book on BC4 as an interactive job you
need to:
1. Open this .org file in emacs.
2. Open a shell (M-x shell) on BC4 over tramp.
3. Start an interactive slurm job on BC4 [[ijob]]
4. Start R in this shell and run `M-x ess-remote` to connect to the
   ess session.

#+NAME: ijob
#+PROPERTY: header-args :eval never-export
#+BEGIN_SRC bash
srun --nodes=1 --ntasks-per-node=1 --mem=10G --time=04:00:00 --pty bash -i
#+END_src


The R code that is part of one R session block will have its src_code
block labelled source: \*shell*. In order to recreate the published
results the R code needs to be run sequentially in order.


* Aim of the analysis

This analysis is part of the study of genetics of scaring using the
ALSPAC cohort.

** Background

When tissues are damaged after birth, the wound healing process is
complex and results in fibrotic scars. 
These scars can lead to loss of function in the tissue.

* Setting up the Phenotype data.

* Gemma
