#+TITLE: Genome Wide Association Study of Scar Size in ALSPAC
#+AUTHOR: Sam Neaves

* About

This notebook is written as an [[https://orgmode.org][emacs Org file]] and exported into HTML
and PDF formats. 
Org files are plain text and can be viewed with any plain text file
viewer. 
In addition if the file is opened in emacs, interactive features of
running the code in the code blocks can be used using a feature called
[[https://orgmode.org/worg/org-contrib/babel/][org babel]].
The GIT hub repositry is https://github.com/samwalrus/gwas_scar
Code blocks are in bash, R and Prolog (only the subset required for
defining makeprog files for Biomake.)


** Initial Setup for interactive code.

To run the R code in this note book on BC4 as an interactive job you
need to:
1. Open this .org file in emacs.
2. Open a shell (M-x shell) on BC4 over tramp.
3. Start an interactive slurm job on BC4 [[ijob]]
4. Start R in this shell and run `M-x ess-remote` to connect to the
   ess session.

#+NAME: ijob
#+PROPERTY: header-args :eval never-export
#+BEGIN_SRC bash
srun --nodes=1 --ntasks-per-node=1 --mem=10G --time=04:00:00 --pty bash -i
#+END_src


The R code that is part of one R session block will have its src_code
block labelled source: \*shell*. In order to recreate the published
results the R code needs to be run sequentially in order.


* Aim of the analysis

This analysis is part of the study of genetics of scaring using the
ALSPAC cohort.

** Background

When tissues are damaged after birth, the wound healing process is
complex and results in fibrotic scars. 
These scars can lead to loss of function in the tissue.

* Setting up the Phenotype data.

* Gemma
